version: '3'

services:
  web:
    build: .
    ports:
      - "8000:10000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - worker

  redis:
    image: redis:6.2

  worker:
    build: .
    command: celery -A worker worker --loglevel=info
    depends_on:
      - redis